const data = {
  products: [
    {
      name: 'Nike slim shirt',
      slug: 'nike-slug-shirt',
      image: '/images/p1.jpg',
      category: 'shirts',
      price: '120',
      countInStock: '10',
      brand: 'Nike',
      rating: 4.5,
      numreviews: 10,
      description: 'high quality products',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-shirt',
      image: '/images/p2.jpg',
      category: 'shirts',
      price: '200',
      countInStock: '10',
      brand: 'adidas',
      rating: 4.7,
      numreviews: 5,
      description: 'high quality products',
    },
    {
      name: 'Adidas pant',
      slug: 'adidas-pant',
      image: '/images/p3.jpg',
      category: 'pants',
      price: '120',
      countInStock: '13',
      brand: 'adidas',
      rating: 4.0,
      numreviews: 12,
      description: 'high quality products',
    },
    {
      name: 'Dior Pants',
      slug: 'dior-pant',
      image: '/images/p4.jpg',
      category: 'pants',
      price: '150',
      countInStock: '25',
      brand: 'Dior',
      rating: 4.5,
      numreviews: 7,
      description: 'high quality products',
    },
  ],
};

export default data;
